websach/Areas/Admin/Controllers/QuanLyController.cs
using sach_Controller;
using Sach_value;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace websach.Areas.Admin.Controllers
{
    public class QuanLyController : BaseController
    {
        // GET: Admin/QuanLy

        public ActionResult ThemTuSach()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemTuSach(TudachValue ts)
        {
            bool kt = new TusachController().InsertElement(ts);
            if (kt == true)
            {
                return RedirectToAction("DanhSachTuS");
            }
            return View();
        }

        public ActionResult DanhSachTuS()
        {

            List<TudachValue> listts = new TusachController().getElements();
         


            return View(listts);
        }

        public ActionResult XoaTuSach(string idxoa)
        {

            Guid idtusach = Guid.Parse(idxoa);

            bool kq = new TusachController().XoaTuSachTheoID(idtusach);
            if (kq == false)
            {
                ModelState.AddModelError("loisukhongduoc", "Không Thể Sửa Được");
                return RedirectToAction("DanhSachTuS");
            }



            return RedirectToAction("DanhSachTuS");
        }
        [HttpGet]
        public ActionResult SuaTuSach(string idsua)
        {
            Guid IDtus = Guid.Parse(idsua);

            TudachValue tsvl = new TusachController().LayTuSachID(IDtus);


            return View(tsvl);


        }
        [HttpPost]
        public ActionResult SuaTuSach(TudachValue sach)
        {
            bool kq = new TusachController().SuaTuSach(sach);
            if (kq == false)
            {
                ModelState.AddModelError("Loi", "Không thể sửa được");
                return View();
            }

            return RedirectToAction("DanhSachTuS");


        }


        public ActionResult ThemSach()
        {
            ViewBag.Tusach = new TusachController().getElements();

            return View();
        }
        

        [HttpPost]
        public ActionResult ThemSach(HttpPostedFileBase HinhAnh,sachvalue sach)
        {


            string gui = Guid.NewGuid().ToString();
            string Filename = gui + Path.GetFileName(HinhAnh.FileName);
            string path = Path.Combine(Server.MapPath("/Areas/Admin/containt/Image/"), Filename);
            HinhAnh.SaveAs(path);
            sach.HinhAnh = "/Areas/Admin/containt/Image/" + Filename;
            bool tc= new SachController().InsertElement(sach);
            

            return RedirectToAction("ListSach");
        }


        public ActionResult ListSach()
        {
            List<sachvalue> listsach = new SachController().getElements();


            return View(listsach);
         }

      [HttpPost]
        public JsonResult XoaSach(string id)
        {

            Guid IDSach = Guid.Parse(id);

            bool kqxoa = new SachController().XoaSachTheoID(IDSach);
            if (kqxoa == true)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }


            return Json(false, JsonRequestBehavior.AllowGet);
            
        }



        public ActionResult SuaSach(string id)
        {
            Guid Idsach = Guid.Parse(id);

            sachvalue sach = new SachController().LaySachTheoID(Idsach);
           List<TudachValue> tusach = new TusachController().getElements();

            ViewBag.Tusach = tusach;

            
            return View(sach);
        }


        [HttpPost]
        public ActionResult SuaSach(HttpPostedFileBase HinhAnh, sachvalue sach)
        {

            string gui = Guid.NewGuid().ToString();
            string Filename = gui + Path.GetFileName(HinhAnh.FileName);
            string path = Path.Combine(Server.MapPath("/Areas/Admin/containt/Image/"), Filename);
            HinhAnh.SaveAs(path);
            sach.HinhAnh = "/Areas/Admin/containt/Image/" + Filename;

            bool kqsua = new SachController().SuaSach(sach);
            if (kqsua == true)
            {
                return RedirectToAction("ListSach");
            }


            return View();
        }
        public ActionResult InfoUser()
        {

            var data = (taikhoan)Session[CommonConstants.SESSION_ACCOUNT];

            return View("~/Areas/Admin/Views/QuanLy/InfoUser.cshtml",data);
        }




        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public JsonResult UpdateMatKhau(taikhoan tk )
        {
            tk.id = ((taikhoan)Session[CommonConstants.SESSION_ACCOUNT]).id;
            bool kq = new TaikhoanController().UpdateMatKhau(tk);
            if (kq == true)
            {
                return Json("Cap Nhap Thanh cong", JsonRequestBehavior.AllowGet);

            }

            return Json("Cap nhat khong thanh cong", JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult UpdateHinhanh(HttpPostedFileBase file)
        {
            taikhoan tk = new taikhoan();

            tk.id=((taikhoan)Session[CommonConstants.SESSION_ACCOUNT]).id;
            string gui = Guid.NewGuid().ToString();
            string Filename = gui + Path.GetFileName(file.FileName);
            string path = Path.Combine(Server.MapPath("/Areas/Admin/containt/Image/"), Filename);
            file.SaveAs(path);
            tk.hinhanh = "/Areas/Admin/containt/Image/" + Filename;

          bool kq=   new TaikhoanController().UpdateHinhAnh(tk);
            if (kq == true)
            {
                
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        }


    }
}

websach/Controllers/QuanLyController.cs
using Sach_value;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace websach.Controllers
{
    public class QuanLyController : Controller
    {
        // GET: QuanLy
       



    }
}

websach/Areas/Admin/Views/QuanLy/DanhSachTuS.cshtml
@model IEnumerable<Sach_value.TudachValue>


<h2>Danh sách tủ sách</h2>
@Html.ValidationMessage("loisukhongduoc")
<table class="table table-bordered">
    <thead>
        <tr>
           
            <td>Tên Tủ Sách</td>
            <td>Chức Năng</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                
                <th>@item.TenTuSach</th>
                <th>
                    @Html.ActionLink("Xóa", "XoaTuSach", "QuanLy", new { idxoa = item.ID }, "")
                    @Html.ActionLink("Sửa", "SuaTuSach", "QuanLy", new { idsua = item.ID },"")
                </th>
            </tr>
        }

    </tbody>
</table>

@Html.ActionLink("Thêm Mới", "ThemTuSach", "QuanLy")

websach/Areas/Admin/Views/QuanLy/InfoUser.cshtml

@model  Sach_value.taikhoan


<div class="profile-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light">
                <div class="portlet-title tabbable-line">
                    <div class="caption caption-md">
                        <i class="icon-globe theme-font hide"></i>
                        <span class="caption-subject font-blue-madison bold uppercase">Profile Account</span>
                    </div>
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#tab_1_1" data-toggle="tab">Personal Info</a>
                        </li>
                        <li>
                            <a href="#tab_1_2" data-toggle="tab">Change Avatar</a>
                        </li>
                        <li>
                            <a href="#tab_1_3" data-toggle="tab">Change Password</a>
                        </li>
                        <li>
                            <a href="#tab_1_4" data-toggle="tab">Privacy Settings</a>
                        </li>
                    </ul>
                </div>
                <div class="portlet-body">
                    <div class="tab-content">
                        <!-- PERSONAL INFO TAB -->
                        <div class="tab-pane active" id="tab_1_1">
                            <form role="form" action="#">

                                <div class="form-group">
                                    <label class="control-label">Điện Thoại</label>
                                    <input type="text" name="dienthoai" placeholder="@Model.dienthoai" class="form-control"  />
                                </div>

                                <div class="form-group">
                                    <label class="control-label">Email</label>
                                    <input type="text" name="email" placeholder="@Model.email" class="form-control" />
                                </div>

                                <div class="margiv-top-10">
                                    <a href="javascript:;" class="btn green-haze">
                                        Save Changes
                                    </a>
                                    <a href="javascript:;" class="btn default">
                                        Cancel
                                    </a>
                                </div>
                            </form>
                        </div>
                        <!-- END PERSONAL INFO TAB -->
                        <!-- CHANGE AVATAR TAB -->
                        <div class="tab-pane" id="tab_1_2">
                            <p>
                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
                            </p>
                            <form action="/Admin/QuanLy/UpdateHinhanh" role="form" method="post" enctype="multipart/form-data">
                                <div class="form-group">
                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                        <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                            <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" id="blah" />
                                        </div>
                                        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
                                        </div>
                                        <div>
                                            <span class="btn default btn-file">
                                                <span class="fileinput-new">
                                                    Select image
                                                </span>
                                                <span class="fileinput-exists">
                                                    Change
                                                </span>
                                                <input type="file" name="file" id="imgInp">
                                            </span>
                                            <a href="javascript:;" class="btn default fileinput-exists" data-dismiss="fileinput">
                                                Remove
                                            </a>
                                        </div>
                                    </div>
                                    <div class="clearfix margin-top-10">
                                        <span class="label label-danger">NOTE! </span>
                                        <span>Attached image thumbnail is supported in Latest Firefox, Chrome, Opera, Safari and Internet Explorer 10 only </span>
                                    </div>
                                </div>
                                <div class="margin-top-10">

                                    <button class="btn green-haze">Submit</button>

                                    <a href="javascript:;" class="btn default">
                                        Cancel
                                    </a>
                                </div>
                            </form>
                        </div>
                        <!-- END CHANGE AVATAR TAB -->
                        <!-- CHANGE PASSWORD TAB -->
                        <div class="tab-pane" id="tab_1_3">
                            <form action="#">
                                <div class="form-group">
                                    <label class="control-label">Nhập Mật Khẩu</label>
                                    <input type="password" name="rmatkhau" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Nhâp Mật Khẩu Mới</label>
                                    <input type="password" id="mkmoi" name="matkhau" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Re-type New Password</label>
                                    <input type="password" class="form-control" />
                                </div>
                                <div class="margin-top-10">
                                    <a id="updateMatKhau" class="btn green-haze">
                                        Change Password
                                    </a>
                                    <a href="javascript:;" class="btn default">
                                        Cancel
                                    </a>
                                </div>
                            </form>
                        </div>
                        <!-- END CHANGE PASSWORD TAB -->
                        <!-- PRIVACY SETTINGS TAB -->
                        <div class="tab-pane" id="tab_1_4">
                            <form action="#">
                                <table class="table table-light table-hover">
                                    <tr>
                                        <td>
                                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus..
                                        </td>
                                        <td>
                                            <label class="uniform-inline">
                                                <input type="radio" name="optionsRadios1" value="option1" />
                                                Yes
                                            </label>
                                            <label class="uniform-inline">
                                                <input type="radio" name="optionsRadios1" value="option2" checked />
                                                No
                                            </label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Enim eiusmod high life accusamus terry richardson ad squid wolf moon
                                        </td>
                                        <td>
                                            <label class="uniform-inline">
                                                <input type="checkbox" value="" /> Yes
                                            </label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Enim eiusmod high life accusamus terry richardson ad squid wolf moon
                                        </td>
                                        <td>
                                            <label class="uniform-inline">
                                                <input type="checkbox" value="" /> Yes
                                            </label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Enim eiusmod high life accusamus terry richardson ad squid wolf moon
                                        </td>
                                        <td>
                                            <label class="uniform-inline">
                                                <input type="checkbox" value="" /> Yes
                                            </label>
                                        </td>
                                    </tr>
                                </table>
                                <!--end profile-settings-->
                                <div class="margin-top-10">
                                    <a href="javascript:;" class="btn green-haze">
                                        Save Changes
                                    </a>
                                    <a href="javascript:;" class="btn default">
                                        Cancel
                                    </a>
                                </div>
                            </form>
                        </div>
                        <!-- END PRIVACY SETTINGS TAB -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section capnhat {
    <script>

        $("#updateMatKhau").click(() => {
            alert("xuat");

            matk = $("#mkmoi").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateMatKhau", "QuanLy")',
                data: `{ matkhau:${matk}}`,
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    alert(data);
                },
                error: function () {
                    alert("Error while inserting data");
                }
            });
        });


        $("#imgInp").change(function () {
            readURL(this);
        });


        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }




    </script>


}

websach/Areas/Admin/Views/QuanLy/ListSach.cshtml
@model IEnumerable<Sach_value.sachvalue>

@{
    ViewBag.Title = "ListSach";
}

<h2>ListSach</h2>

<p>
    @Html.ActionLink("Thêm Sách Mới", "ThemSach", "QuanLy")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tensach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tacgia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoTrang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kho)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhaXuatBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenTuSach)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Tensach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tacgia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoTrang)
        </td>
        <td>
           <img src="@item.HinhAnh" alt="không có hình"  width="178px" height="160px"  />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kho)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhaXuatBan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenTuSach)
        </td>
        <td>
            <a href="@Url.Action("SuaSach","QuanLy",new {id=item.id })" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Sửa Sản Phẩm</a>

            <a onclick="xoasach('@item.id','@item.Tensach')" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Xóa Sách</a>

        </td>
    </tr>
}

</table>


<script >

 
    function xoasach(idxoa,tensach) {

        var r = confirm(`Bạn có muốn xóa sản phẩm ${tensach}`);
        if (r == true) {
            $.ajax({
                url: "@Url.Action("XoaSach","QuanLy")",
                type: "POST",
                data: {
                    id: idxoa
                },
                success: function (result) {
                    if (result) {
                        window.location.reload();
                    }
                    else {
                        alert("Thất bại")
                    }
                }
            });
        }
        else {
            window.location.reload();
        }
       
    }

   

</script>

websach/Areas/Admin/Views/QuanLy/SuaSach.cshtml
@model Sach_value.sachvalue
@{
    var tusach = ViewBag.Tusach as List<Sach_value.TudachValue>;
    
}

<h2>Chỉnh Sửa Sách</h2>

@using (Html.BeginForm("SuaSach", "QuanLy", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.TextBoxFor(m => m.id, new { @class = "form-control ", @type = "hidden"})

    <div class="form-group">
        @Html.LabelFor(m => m.Tensach)
        @Html.TextBoxFor(m => m.Tensach, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Tacgia)
        @Html.TextBoxFor(m => m.Tacgia, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Gia)
        @Html.TextBoxFor(m => m.Gia, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SoTrang)
        @Html.TextBoxFor(m => m.SoTrang, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Kho)
        @Html.TextBoxFor(m => m.Kho, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NhaXuatBan)
        @Html.TextBoxFor(m => m.NhaXuatBan, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NgayPhatHanh)
      @Html.TextBoxFor(m=>m.NgayPhatHanh,new {@class= "form-control",@type="date" })
    </div>
    <div class="form-group">
        <h3>Ảnh</h3>
        @Html.TextBoxFor(m => m.HinhAnh, new { type = "file", name = "HinhAnh", id = "avatar" })
        <div style="margin-top:15px;">
            <img style="width:200px;height:150px;" id="hinhanh" class="img-thumbnail rimage" src="@Model.HinhAnh" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m=>m.TenTuSach)
        @{ 
            List<SelectListItem> ListTuSach = new List<SelectListItem>();
            foreach (var item in tusach)
            {
                ListTuSach.Add(new SelectListItem() {
                    Value=""+item.ID,
                    Text=item.TenTuSach,
                    
                    
                });
            }
        }
        @Html.DropDownListFor(m=>m.idtusach, ListTuSach,new { @class= "form-control" })
     


    </div>

    @Html.TextBox("LuuLai", "Lưu Lại", new { @type = "submit" });

}


@section SuaSach{

    <script type="text/javascript">
        $("#avatar").change(function () {

            readURL(this);
        });


        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#hinhanh').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        if (window.location.hostname) {
            alert(Xuat);
        }


    </script>


}

websach/Areas/Admin/Views/QuanLy/SuaTuSach.cshtml
@model Sach_value.TudachValue

<h2>CHỈNH SỬA TỦ SÁCH</h2>

@using (Html.BeginForm("SuaTuSach","QuanLy",FormMethod.Post))
{
<div class="form-group">
    @Html.TextBoxFor(m => m.ID, new { @class = "form-control ",@type="hidden" })
    @Html.LabelFor(m => m.TenTuSach)
    @Html.TextBoxFor(m => m.TenTuSach, new { @class = "form-control" })
</div>
 @Html.TextBoxFor(m=>m.TenTuSach, new  {@type= "submit" })
}



websach/Areas/Admin/Views/QuanLy/ThemSach.cshtml


@{
   var  listtusach = ViewBag.Tusach as List<Sach_value.TudachValue>;


    ViewBag.Title = "ThemSach";
}

@Html.ActionLink("List Sách ", "ListSach","QuanLy",new {@class= "btn btn-secondary btn-lg active" })

<form method="post" action="/Admin/QuanLy/ThemSach" enctype ="multipart/form-data" >
    <div class="form-group">
        <label for="TenSach">Tên Sách</label>
        <input type="text" class="form-control" id="TenSach" name="Tensach" placeholder="Tên Sách">
    </div>
    <div class="form-group">
        <label for="TacGia">Tác Giả</label>
        <input type="text" class="form-control" id="TacGia" name="Tacgia" placeholder="Tác Giả">
    </div>
    <div class="form-group">
        <label for="Gia">Giá</label>
        <input type="text" class="form-control" id="Gia" name="Gia" placeholder="Giá">
    </div>
    <div class="form-group">
        <label for="SoTrang">Số Trang</label>
        <input type="text" class="form-control" id="SoTrang" name="SoTrang" placeholder="Số Trang">
    </div>
    <div class="form-group">
        <img src="#" width="178px" height="160px" id="hinhsach" alt="không có hình" />
        <div class="form-group">

            <label for="HinhAnh">Thêm Hình Ảnh</label>
            <input type="file" class="form-control-file" id="HinhAnh" name="HinhAnh">
        </div>
    </div>

    <div class="form-group">
        <label for="Kho">Kho</label>
        <input type="text" class="form-control" id="kho" name="Kho" placeholder="Kho">
    </div>

    <div class="form-group">
        <label for="nhaxuatban">Nhà Xuất Bản</label>
        <input type="text" class="form-control" id="nhaxuatban" name="NhaXuatBan" placeholder="Nhà Xuất Bản">
    </div>
    <div class="form-group">
        <label>Ngày Phát Hành</label>
        <input type="date" class="form-control" id="NgayPhatHanh" name="NgayPhatHanh" placeholder="Ngày Phát Hành"/>
    </div>
    <div class="form-group">
        <label for="tusach">Tu Sách</label>
        <select class="form-control" id="tusach" name="idtusach">
            @foreach (var item in listtusach)
            {
                <option value="@item.ID">@item.TenTuSach</option>
            }
          
        </select>
    </div>
    <button type="submit" class="btn btn-primary mb-2">Thêm Sách Mới</button>
</form>



@section Themtusach{

<script type="text/javascript">
    $("#HinhAnh").change(function () {
        readURL(this);
    });


    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#hinhsach').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }


    </script>    
    
}

websach/Areas/Admin/Views/QuanLy/ThemTuSach.cshtml


@using (Html.BeginForm("ThemTuSach","QuanLy",FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Tusach","Thêm tu sách")
    @Html.TextBox("TenTuSach")
    <button type="submit">Lưu</button>
</div>
}

@Html.ActionLink("Danh Sách Tủ Sách", "DanhSachTuS", "QuanLy")